services:

  opensearch:
    image: opensearchproject/opensearch:1.3.18
    container_name: opensearch
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      compatibility.override_main_response_version: true
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - data-network
  
  opensearch-dashboards:
    container_name: opensearch_dashboard
    image: opensearchproject/opensearch-dashboards:1.3.18
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    networks:
      - data-network

networks:
  data-network:
    external: true

