services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: data
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - data-network

networks:
  data-network:
    external: true

volumes:
  mysql-db:
    name: mysql_db