networks:
  cassandra-net:
    driver: bridge
  data-network:
    external: true

services:

  cassandra-1:
    image: "cassandra:4.1.3"  # cassandra:4.1.3
    container_name: "cassandra-1"
    ports:
      - 7001:7000
      - 9042:9042
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=2048M
    volumes:
      - cassandra-node-1:/var/lib/cassandra:rw
    # restart:
    #   on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

volumes:
  cassandra-node-1: