#https://github.com/compose-spec/compose-spec/blob/master/spec.md#using-extensions-as-fragments
x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file

services:
  db:
    image: postgres:16.3
    logging: *default-logging
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - /tmp/postgres/:/var/lib/postgresql/data
    networks:
      - data-network
    ports:
      - "5432:5432"

networks:
  data-network:
    external: true