CREATE USER airbyte PASSWORD 'airbyte_pass';

GRANT USAGE ON SCHEMA public TO airbyte;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO airbyte;
ALTER DEFAULT PRIVILEGES IN SCHEMA  public GRANT SELECT ON TABLES TO airbyte;