# suRun do lsof -i :<PORT> then kill pid

datahub/update:
	./install.sh

datahub/start:
	python3 -m datahub docker quickstart

datahub/stop:
	python3 -m datahub docker quickstart --stop

datahub/backup:
	python3 -m datahub docker quickstart --backup